
BLENDER="C:\Program Files\Blender Foundation\Blender 5.1\blender.exe"
DIST=../dist

all : \
    $(DIST)/hexapod.pnct \
    $(DIST)/hexapod.scene \
    $(DIST)/train_model.pnct \
    $(DIST)/train_model.scene \

$(DIST)/hexapod.scene : hexapod.blend export-scene.py
    $(BLENDER) --background --python export-scene.py -- "hexapod.blend:Main" "$(DIST)/hexapod.scene"

$(DIST)/hexapod.pnct : hexapod.blend export-meshes.py
    $(BLENDER) --background --python export-meshes.py -- "hexapod.blend:Main" "$(DIST)/hexapod.pnct" 

$(DIST)/train_model.scene : train_model.blend export-scene.py
    $(BLENDER) --background --python export-scene.py -- "train_model.blend:Main" "$(DIST)/train_model.scene"

$(DIST)/train_model.pnct : train_model.blend export-meshes.py
    $(BLENDER) --background --python export-meshes.py -- "train_model.blend:Main" "$(DIST)/train_model.pnct" 
